CREATE DATABASE IF NOT EXISTS gitea CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'gitea'@'localhost' IDENTIFIED BY '2020||Saurab';
GRANT ALL PRIVILEGES ON *.* TO 'gitea'@'localhost' ;
FLUSH PRIVILEGES;
